### ISSUE TITLE
Could not load timeZone data on Windows ?

### ISSUE THREAD

**Issue by pratheep15** [Gotham25/hotstar-dl#9]
panic: open **C:\Go/lib/time/zoneinfo.zip**: The system cannot find the path specified.

> hotstardl -l <>
Parsed video url is<>
panic: open C:\Go/lib/time/zoneinfo.zip: The system cannot find the path specified.

goroutine 1 [running]:
github.com/Gotham25/hotstar-dl/utils.GetDateStr(0x41d7caad16000000, 0xc0003d25d0, 0x7c9ccd)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/utils/common.go:46 +0x1ee
github.com/Gotham25/hotstar-dl/utils.PopulateMetaDataMapWithMetadata(0xc0003d25d0, 0xc00006f6a8)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/utils/playbackuri.go:71 +0xaed
github.com/Gotham25/hotstar-dl/utils.GetPlaybackURI(0xc000304000, 0x3295a, 0xc000046240, 0x60, 0xc000046296, 0xa, 0xc000146b70, 0x24, 0x663937647d795e82, 0x3963392d38636631, ...)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/utils/playbackuri.go:170 +0x4ee
github.com/Gotham25/hotstar-dl/utils.getPlayback(0xc000304000, 0x3295a, 0xc000046240, 0x60, 0xc000046296, 0xa, 0xc000146b70, 0x24, 0xa871c0, 0x1fffffffffff, ...)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/utils/videoutils.go:123 +0x91
github.com/Gotham25/hotstar-dl/utils.GetVideoFormats(0xc000046240, 0x60, 0xc000046296, 0xa, 0x0, 0x80, 0xc0000f0180, 0x9, 0xa871c0)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/utils/videoformats.go:36 +0x743
github.com/Gotham25/hotstar-dl/utils.ListVideoFormats(0xc000046240, 0x60, 0xc000046296, 0xa, 0x0, 0xc000080000)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/utils/videoformats.go:81 +0x7e
main.handleNonPlaylistURL(0xc000046240, 0x60, 0xc000046296, 0xa)
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/main.go:134 +0x9f
main.main()
        C:/Users/Gowtham/go/src/github.com/Gotham25/hotstar-dl/main.go:178 +0x121

**Comment by pratheep15** [comment]
I would love to help with coding, let me know if I can get guidance.

**Comment by zenminds** [comment]
Still issue comes for me , have fixed this issue ?
